#####################################################################################
# documentation:
# - https://docs.gitea.com/usage/actions/overview
# - https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
#####################################################################################

name: Gradle build
run-name: Initiated by ${{ gitea.actor }}
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:  # button shown only when in default branch

jobs:
  build:
    runs-on: docker-node-latest

    steps:
    - uses: actions/checkout@v4

    - id: commit
      uses: prompt/actions-commit-hash@v3

    - name: set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: "current"
        gradle-home-cache-cleanup: true

    - name: Build
      run: |
        gradle --no-daemon assemble 
        #find . -name '*.jar' # ./build/libs/cve_checker-0.7.0.jar

    - name: Prep release
      run: |
        cd ./build/libs/
        mv cve_checker-*.jar cve_checker.jar
        sha512sum cve_checker.jar > cve_checker.jar.sha512
        echo "SHA=$(cat cve_checker.jar.sha512 | cut -d ' ' -f1)" >> $GITHUB_ENV
        
        REF_NAME=$(echo "${{ github.ref }}" | sed -e 's/refs\/heads\///' -e 's/refs\/tags\/v//' -e 's/release\/v//')
        echo "Cleaned name is ${REF_NAME}"
        echo "branch=${REF_NAME}" >> "$GITHUB_OUTPUT"
        echo "APP_VERSION=v${REF_NAME}" >> $GITHUB_ENV

    - name: Generate release on MIRROR
      uses: https://gitea.com/actions/gitea-release-action@v1
      with:
        token: "${{ secrets.MIRROR_TOKEN_RW }}"
        tag_name: ${{ env.APP_VERSION }}
        prerelease: false
        server_url: https://${{ vars.MIRROR_ORG_DOMAIN }}
        repository: ${{ vars.MIRROR_RELEASE_ORG_NAME }}/${{ github.event.repository.name }}
        name: "${{ env.APP_VERSION }}"
        body: |
          # CVE Kernel patcher

          |JAR|sha512|
          |-|-|
          |cve_checker.jar|${{ env.SHA }}|

        files: |
            build/libs/cve_checker.jar
            build/libs/cve_checker.jar.sha512